services:
  db:
    image: postgres:16-alpine
    container_name: qa_db
    environment:
      POSTGRES_USER: qa_user
      POSTGRES_PASSWORD: qa_pass
      POSTGRES_DB: qa_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  cache:
    image: redis:7-alpine
    container_name: qa_cache

  adminer:
    image: adminer:latest
    container_name: qa_adminer
    ports:
      - "8888:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
